### ISSUE TITLE
SDDM theme doesn't handle long names properly

### ISSUE THREAD

**Issue by zigapk** [lirios/themes#4]
The name should break in 2 lines or replace the last chars with ... (3 dots).
![sddm_long_name](https://cloud.githubusercontent.com/assets/5074514/19398111/52b4437c-924b-11e6-972e-7a78681eb348.jpg)

**Comment by plfiorini** [comment]
Fixed this is how it looks now:

![screenshot from 2017-02-19 23-00-14](https://cloud.githubusercontent.com/assets/843710/23107106/5b7ecd5e-f6f7-11e6-8432-c9a2058b9b59.png)
![screenshot from 2017-02-19 23-00-22](https://cloud.githubusercontent.com/assets/843710/23107105/5b77930e-f6f7-11e6-8ff4-db60b22b5f46.png)
